version: '3'
services:
  dockercleanup:
    image: amd64/docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host
      - ../etc/dockercleanup/clean.sh:/clean.sh
    entrypoint: /clean.sh
