version: '3'
services:
  portainer:
    image: portainer/portainer
    ports:
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ~/.portainer:/data
  kibana:
    image: "kibana:4.6"
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://10.5.5.23:9200
  dockercleanup:
    image: amd64/docker
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /:/host
    - ./dockercleanup/clean.sh:/clean.sh
    entrypoint: /clean.sh  

